apiVersion: v1
kind: Secret
metadata:
  name: "sonarqube-token"
  namespace: "jenkins"
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
    "jenkins.io/credentials-description" : "secret text credential from Kubernetes"
type: Opaque
stringData:
  sonarqube-token: 0b61a4cb8cb13bc9a5100ca7c628876653315e2d
