apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  namespace: logging
spec:
  type: LoadBalancer
  selector:
    app: fluentd-logging
  ports:
    - protocol: TCP
      port: 9880
      targetPort: 9880
