# #managed by opeomotayo
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: jenkins-ingress
#   namespace: jenkins
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
# spec:
#   tls:
#   - hosts:
#       - jenkins.opeomotayo.net
#     secretName: jenkins-production-certificate
#   rules:
#   - host: jenkins.opeomotayo.net
#     http:
#       paths:
#       - backend:
#           service:
#             name: jenkins
#             port:
#               number: 8080
#         path: /
#         pathType: Prefix
